### ISSUE TITLE
Maxtrix.py - Value error: width * height cannot exceed total pixel count!

### ISSUE THREAD

**Issue by xtalker** [ManiacalLabs/AllPixel#11]
Hey Adam,  I'm trying to get the matrix.py (from https://github.com/ManiacalLabs/AllPixel/wiki/Matrix-Example) working but I get this error:

'Traceback (most recent call last):
  File "matrix.py", line 16, in <module>
    serpentine = True)
  File "/usr/local/lib/python3.5/dist-packages/bibliopixel/layout/matrix.py", line 67, in __init__
    % (self.width, self.height, self.numLEDs))
ValueError: width * height cannot exceed total pixel count! 32 * 32 > 9'

The only line in the example code I changed was:
'driver = Serial(num = 3*3, ledtype = LEDTYPE.WS2812)'
(using a 3x3 Nulsom ns-led-06 led matrix)

Thanks,
Bob

**Comment by adammhaile** [comment]
@xtalker Can you submit that here? https://github.com/ManiacalLabs/BiblioPixel/issues
That's really a BiblioPixel issue.
Though you should be able to set `width=3, height=3` in the `Matrix()` creation.
Looks like another slight regression. So sorry about that. It *should* work the way you say but looks like we missed a couple backwards compatibilities.
