### ISSUE TITLE
Cannot connect my Allpixel

### ISSUE THREAD

**Issue by Wintermute2501** [ManiacalLabs/AllPixel#13]
Hey Adam,

I am trying to reactivate my Allpixel.
Running your Strip Example I get the following response:

WARNING - deprecated - util.setLogLevel
INFO - devices - Using COM Port: COM3, Device ID: 0, Device Ver: 0
WARNING - deprecated - BaseAnimation.run
DEBUG - animation_threading - Animation starts on main thread

Can you please help??

BR, Fabian

**Comment by adammhaile** [comment]
BTW... support requests should go here -> https://groups.google.com/forum/#!forum/maniacal-labs-users

Was there any more to the console output? That looks like it connected... there's no error. It found the device ID and Version (0 and 0 are correct for a new device). Are you just not getting any output on the LEDs?

What version of bibliopixel are you running? Please send the output of `pip list`

**Comment by Wintermute2501** [comment]
Sorry! I did open a topic in Google Groups..

**Comment by adammhaile** [comment]
No worries. I need to find a way to make that more clear here.
