### ISSUE TITLE
Can you help me out how to use AllPixel with the RBG LED strip!

### ISSUE THREAD

**Issue by nikhilrm** [ManiacalLabs/AllPixel#6]
Hi,
Can you tell me the procedure of how to use the AllPixel with an RGB LED strip, which also has 4 terminals, for 12V, R,G & B. I would love to use the strip too.

Thanks in advance
Nikhil

**Comment by adammhaile** [comment]
Nikhil,

What you are talking about is an analog LED strip but the AllPixel is for
digital strips which have LED driver ICs built in. What you want to do is
not currently possible. If there is enough interest we may release a
product for analog strips as well.

Check the wiki docs for a list of digital strip types that are compatible
with the AllPixel

-Adam

**Comment by adammhaile** [comment]
Nikhil,

FYI, we have a product for analog LED strips now:
https://www.kickstarter.com/projects/maniacallabs/longpixel-digital-control-for-analog-led-strips/
