### ISSUE TITLE
Threaded run not working

### ISSUE THREAD

**Issue by jimnet2005** [ManiacalLabs/AllPixel#7]
This is an issue related to the /dev branch. When trying to run an animation using the "threaded  = True" method: the thread simply does not run. The issue is related to the line 156 of animation.py, in which you get the locals() dictionary. Within the following lines you attempt to remove some members from the locals() dictionary which seems to be an invalid operation as even the local "self" reference is removed.

The best workaround I've seen for this is replacing the line 156 with the following:

args =  locals().copy()    # gets a copy of the locals() instead of the actual locals

Regards,

Jaime

**Comment by jimnet2005** [comment]
Will report this issue in BiblioPixel

**Comment by adammhaile** [comment]
The dev branch is... well, not fit for consumption as it's in constant
flux. Any particular reason you are using it? (Forgive me if I forgot about
some previous conversation).
Also, could you send me the basic code you are using and on with what
system details? I'm not seeing it fail on my end... although, I think I see
what you mean and am putting in a fix. I'm guessing that on some version of
python or systems, locals() gets the actual dictionary in use and then
modifies it... which is obviously bad.

**Comment by jimnet2005** [comment]
You can close this as I opened another thread in Bibliopixel
