### ISSUE TITLE
Installation instructions appear to be outdated

### ISSUE THREAD

**Issue by drbrain** [ManiacalLabs/AllPixel#8]
The AllPixel [Library Install and Strip Example](https://github.com/ManiacalLabs/AllPixel/wiki/Library-Install-and-Strip-Example) instructions say:

> IMPORTANT: Python 2.7.x is REQUIRED. BiblioPixel is NOT 3.x compatible!

But the [BiblioPixel Installation page](https://github.com/ManiacalLabs/BiblioPixel/wiki/Installation) says:

> BiblioPixel v3 requires Python 3.4 or higher

but also mentions a BiblioPixel 2:

> if your application requires Python 2, then there's an unsupported legacy BiblioPixel 2 that works with Python 2.7.

After this using the latest version of BiblioPixel which requires Python 3 the demo program will not run, this appears to be the correct program:

```python
import bibliopixel
# causes frame timing information to be output
bibliopixel.log.setLogLevel(bibliopixel.log.DEBUG)

# Load driver for the AllPixel
from bibliopixel.drivers.serial import *
# set number of pixels & LED type here
driver = Serial(num = 10, type = LEDTYPE.WS2812B)

# load the LEDStrip class
from bibliopixel.layout import *
led = Strip(driver)

# load channel test animation
from bibliopixel.animation import StripChannelTest
anim = StripChannelTest(led)

try:
    # run the animation
    anim.run()
except KeyboardInterrupt:
    # Ctrl+C will exit the animation and turn the LEDs offs
    led.all_off()
    led.update()
```

The update includes consistent indentation and space between comment character and comment to improve readability.

**Comment by adammhaile** [comment]
@drbrain - Thanks for pointing that out! BiblioPixel 3.0 has been a huge push to get done and we were still playing catch-up a bit. I'll go through the wiki again now and clean it up.
Thanks for the updated code too! :) Saves me some time.
Will close this out once I've updated everything.

**Comment by adammhaile** [comment]
Ok... everything should be updated to reflect BP 3.0. Thanks for pointing that out!
